// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/config/project-path": {
            "get": {
                "description": "현재 설정된 프로젝트 경로를 조회합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "프로젝트 경로 조회 (v1.2)",
                "responses": {
                    "200": {
                        "description": "프로젝트 경로 정보",
                        "schema": {
                            "$ref": "#/definitions/server.ProjectPathResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "cursor-agent가 실행될 프로젝트 경로를 설정합니다.\n이 경로는 런타임에 동적으로 변경 가능합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "프로젝트 경로 설정 (v1.2)",
                "parameters": [
                    {
                        "description": "프로젝트 경로",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ProjectPathRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "경로 설정 성공",
                        "schema": {
                            "$ref": "#/definitions/server.ProjectPathResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/cursor": {
            "post": {
                "description": "JSON 형식으로 cursor-agent를 실행합니다. Slack 인증이 필요 없습니다.\nv1.1: 자연어 프롬프트 방식 (파일명을 프롬프트에 직접 포함)\nasync=false: 동기 실행 (결과를 즉시 반환)\nasync=true: 비동기 실행 (job_id만 반환, 결과는 별도 조회 필요 - 원 단계에서 구현)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "일반 API를 통한 Cursor Agent 실행 (v1.1)",
                "parameters": [
                    {
                        "description": "Cursor 실행 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.APICursorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "실행 성공",
                        "schema": {
                            "$ref": "#/definitions/server.APICursorResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/jobs": {
            "get": {
                "description": "작업 목록을 조회합니다. 상태별 필터링과 페이지네이션을 지원합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "작업 목록 조회 (v1.3)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "조회할 개수 (기본값: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "건너뛸 개수 (기본값: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "작업 상태 필터 (pending/running/completed/failed)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "작업 목록",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.JobRecord"
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/jobs/{id}": {
            "get": {
                "description": "Job ID로 작업 실행 결과를 조회합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "작업 결과 조회 (v1.3)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "작업 결과",
                        "schema": {
                            "$ref": "#/definitions/database.JobRecord"
                        }
                    },
                    "404": {
                        "description": "작업을 찾을 수 없음",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "서버가 정상 동작 중인지 확인합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "서버 상태 확인",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/slack/cursor": {
            "post": {
                "security": [
                    {
                        "SlackSignature": []
                    },
                    {
                        "SlackTimestamp": []
                    }
                ],
                "description": "Slack의 /cursor 슬래시 커맨드를 받아 cursor-agent를 비동기로 실행합니다.\nv1.1: 자연어 프롬프트 방식 사용 (파일명을 프롬프트에 직접 포함)\nHMAC-SHA256 서명 검증 및 타임스탬프 검증이 필요합니다.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Slack 슬래시 커맨드 처리 (v1.1)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "자연어 프롬프트 (예: 'main.go의 버그를 수정해줘')",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Slack 사용자명",
                        "name": "user_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Slack 사용자 ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "지연 응답을 보낼 Slack Webhook URL",
                        "name": "response_url",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Slack 트리거 ID",
                        "name": "trigger_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "즉시 ACK 응답",
                        "schema": {
                            "$ref": "#/definitions/server.SlackImmediateResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.JobRecord": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "description": "milliseconds",
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "project_path": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/database.JobStatus"
                },
                "user_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "database.JobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "JobStatusPending",
                "JobStatusRunning",
                "JobStatusCompleted",
                "JobStatusFailed"
            ]
        },
        "server.APICursorRequest": {
            "type": "object",
            "required": [
                "prompt"
            ],
            "properties": {
                "async": {
                    "type": "boolean",
                    "example": false
                },
                "prompt": {
                    "type": "string",
                    "example": "main.go의 버그를 수정해줘"
                }
            }
        },
        "server.APICursorResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "Cursor AI 작업이 완료되었습니다."
                },
                "output": {
                    "type": "string",
                    "example": "// 실행 결과 출력"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request payload"
                }
            }
        },
        "server.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "server.ProjectPathRequest": {
            "type": "object",
            "required": [
                "path"
            ],
            "properties": {
                "path": {
                    "type": "string",
                    "example": "/Users/username/projects/my-project"
                }
            }
        },
        "server.ProjectPathResponse": {
            "type": "object",
            "properties": {
                "is_set": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "프로젝트 경로가 설정되었습니다."
                },
                "path": {
                    "type": "string",
                    "example": "/Users/username/projects/my-project"
                }
            }
        },
        "server.SlackImmediateResponse": {
            "type": "object",
            "properties": {
                "response_type": {
                    "type": "string",
                    "example": "ephemeral"
                },
                "text": {
                    "type": "string",
                    "example": "⏳ 요청을 접수했습니다. 작업을 처리 중입니다..."
                }
            }
        }
    },
    "securityDefinitions": {
        "SlackSignature": {
            "description": "Slack HMAC-SHA256 서명",
            "type": "apiKey",
            "name": "X-Slack-Signature",
            "in": "header"
        },
        "SlackTimestamp": {
            "description": "Slack 요청 타임스탬프 (Unix timestamp)",
            "type": "apiKey",
            "name": "X-Slack-Request-Timestamp",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.3",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Slack-Cursor-CLI API (v1.3)",
	Description:      "Slack 슬래시 커맨드를 통해 Cursor Agent를 실행하는 서버입니다.\nv1.3: SQLite 작업 결과 저장 및 조회\nv1.2: 동적 프로젝트 경로 관리 (런타임 설정/변경)\nv1.1: 자연어 프롬프트 방식, Process Group 관리, SSRF 방어\n주요 기능: HMAC 인증 + 비동기 실행 + 보안 강화 + 동적 경로 관리 + 작업 결과 저장",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
